const proofData = require('../../zokrates/code/square/0/proof.json');
// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const Verifier = artifacts.require('Verifier');

// - use the contents from proof.json generated from zokrates steps
const { proof, inputs } = proofData;
const { a, b, c } = proof;

contract('TestSquareVerifier', accounts => {
    describe('test verifier contract', function () {
        beforeEach(async function () { 
            this.contract = await Verifier.new();
        })

        // Test verification with correct proof
        it('should verify a correct proof', async function () {
            let proveCorrectness = await this.contract.verifyTx.call(a, b, c, inputs);
            assert(proveCorrectness, "Should verify as correct.");
        })

        // Test verification with incorrect proof
        it('should reject an incorrect proof', async function () {
            let proveIncorrectness = await this.contract.verifyTx.call(a, b, a, inputs);
            assert(!proveIncorrectness, "Should fail to verify an incorrect proof.");
        })
    })
});
